[package]
name = "cal"
version = "0.1.0"
authors = ["Rafael Epplée <hello@rafa.ee>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
